# Generated by Django 4.0 on 2022-01-03 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
                ('runtime', models.IntegerField()),
                ('episodes', models.IntegerField()),
                ('timestop', models.IntegerField()),
                ('progress', models.IntegerField()),
            ],
        ),
    ]
