# Generated by Django 4.0 on 2022-01-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_show_episodes_alter_show_progress_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='episodes',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='progress',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='runtime',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='show',
            name='timestop',
            field=models.CharField(max_length=50),
        ),
    ]
